"""
Agent 6: Analytics Agent
Generates urban traffic statistics, calculates carbon emissions (CO2), peak performance scores, and sustainability metrics.
"""
import json
from datetime import datetime
from typing import Dict, Any
try:
    from crewai import Agent
except Exception:
    Agent = None
from config.settings import get_llm


def create_analytics_agent() -> Agent:
    """Factory to create CrewAI Analytics Agent."""
    llm = get_llm()
    return Agent(
        role="Analytics Agent",
        goal="Generate traffic analytics reports, evaluate road performance index, estimate carbon emissions, and provide sustainability insights.",
        backstory=(
            "You are a Transportation Sustainability & Data Analytics AI. You compile long-term traffic metrics, "
            "compute fuel waste and carbon footprint (CO2 kg) generated by idling vehicles in traffic gridlocks, "
            "and measure overall network optimization efficiency."
        ),
        verbose=True,
        memory=True,
        llm=llm
    )


def process_analytics_rule_based(traffic_report: Dict[str, Any], congestion_info: Dict[str, Any], signal_info: Dict[str, Any]) -> Dict[str, Any]:
    """Deterministic fallback logic for Analytics Agent."""
    road = traffic_report.get("road", "Main Road")
    vehicles = traffic_report.get("vehicles", 50)
    avg_speed = traffic_report.get("average_speed", 40.0)
    congestion_score = congestion_info.get("congestion_score", 40.0)
    density = traffic_report.get("density", "Medium")

    idle_factor = 2.2 if avg_speed < 30 else (1.4 if avg_speed < 45 else 1.0)
    carbon_emission = round(vehicles * 0.25 * idle_factor, 2)

    perf_score = max(0.0, min(100.0, 100.0 - congestion_score * 0.7 + (avg_speed / 60.0) * 20.0))
    perf_score = round(perf_score, 1)

    insights = [
        f"Vehicle flow rate: {vehicles} vehicles/hour on {road}.",
        f"Estimated Carbon Footprint for this cycle: {carbon_emission} kg CO2.",
        f"Road Efficiency Index scored at {perf_score}/100."
    ]

    if signal_info.get("estimated_wait_time_reduction_pct", 0) > 20:
        insights.append(f"Dynamic signal timing saved approx. {round(vehicles * 0.08, 1)} kg CO2 emissions by reducing idle delay.")

    return {
        "timestamp": datetime.utcnow().isoformat(),
        "road_name": road,
        "vehicle_count": vehicles,
        "average_speed": avg_speed,
        "congestion_level": density,
        "carbon_emission_kg": carbon_emission,
        "road_performance_score": perf_score,
        "key_insights": insights
    }
